<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/Cliente.inc";
                     
class Cliente_Model extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    
    /** 
     * @abstract Funcion para obtener un cliente(s) 
     * @return Lista de Structure_ClienteGeneral
     */
    function GetCliente($_idCliente)
    {
        $sql = "SELECT * FROM `cliente` WHERE hash='".$_idCliente."'";

        $res = $this->Execute($sql);

        if ($this->ContainsData($res))
        {
            $row = $this->FetchArray($res);

            $idCliente = $row["idCliente"];

            return $idCliente;

        }
        else
        {
            return false;
        }
    }
    function GetListCliente()
    {
        $sql = "SELECT * FROM `view_cliente_general_activo` order by idCliente";
        $res = $this->Execute($sql);
        
        $list = array();
        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);            
            
            foreach($data as $item)
            {
                $osClienteGeneral = new Structure_ClienteGeneral;

 				$osClienteGeneral->idCliente->SetValue($item["idCliente"]);
 				$osClienteGeneral->nombreCompleto->SetValue($item["NombreCompleto"]);
 				$osClienteGeneral->nroDocumento->SetValue($item["NroDocumento"]);
                $osClienteGeneral->direccion->SetValue($item["Direccion"]);
                $osClienteGeneral->celular->SetValue($item["Celular"]);
                $osClienteGeneral->tipoCliente->SetValue($item["tipoCliente"]);
                $list[] = $osClienteGeneral;

            }            
        }
        return $list;
    }
    function SaveCliente($_osCliente)
    {
        $sql = "INSERT INTO cliente VALUES(
				".$_osCliente->idCliente->GetValue().",
                '".$_osCliente->hash->GetValue()."',
				'".$_osCliente->direccion->GetValue()."',
                '".$_osCliente->zona->GetValue()."',
				'".$_osCliente->tel_fijo->GetValue()."',
                '".$_osCliente->tel_celular->GetValue()."',
                '".$_osCliente->fecha_reg->GetValue()."',
                '".$_osCliente->estado->GetValue()."')";
        $res = $this->Execute($sql);

		$id   = $this->GetLastIdAutoGenerated();
        $hash = sha1($id);
        $sql2 = "Update cliente set hash = '". $hash ."' where idCliente = " . $id;
        $res2 = $this->Execute($sql2);
        
        $r = ($res and $res2) ? true : false;
		
		return $id;
    }
    function DeleteCliente($_idCliente)
    {
        $sql = "Update cliente set estado = 'Inactivo' where hash ='".$_idCliente."'";
        $res = $this->Execute($sql);
        
        return $res;
    }
    function UpdateCliente($_osCliente)
    {
        $sql = "Update cliente set 
					direccion = '" . $_osCliente->direccion->GetValue() . "',
                    zona = '" . $_osCliente->zona->GetValue() . "',
                    tel_fijo = '" . $_osCliente->tel_fijo->GetValue() . "',
                    tel_celular = '" . $_osCliente->tel_celular->GetValue(). "',
                    estado = '" . $_osCliente->estado->GetValue(). "'
				where hash = '" . $_osCliente->hash->GetValue() . "'";
        $res = $this->Execute($sql);

        if ($res == true) 
        {
            $sql2 = "SELECT * FROM cliente where hash='".$_osCliente->hash->GetValue()."'";
            
            $res2 = $this->Execute($sql2);

            if ($this->ContainsData($res2)) 
            {
                $row = $this->FetchArray($res2);

                $idCliente = $row["idCliente"];

                return $idCliente;
            } 
        }
        else
        {
            return false;
        }

    }
    function ActiveCliente($_idCliente)
    {
        $sql = "Update cliente set estado = 'Activo' where hash ='".$_idCliente."'";
        $res = $this->Execute($sql);
        
        return $res;
    }
}
                
?>