<?php
require_once "data/db.inc";
require_once "data/Proveedor.inc";



class Proveedor_Model extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    
    function GetProveedorList()
    {
        $sql = "SELECT * FROM `proveedor`";

        $res = $this->Execute($sql);

        $listaProveedor = array();

        if ($this->ContainsData($res))
        {
            $data = $this->DataListStructure($res);
            
            foreach($data as $item)
            {
                $osProveedor = new Structure_Proveedor;

                $osProveedor->idProveedor->SetValue($item["idProveedor"]);
                $osProveedor->hash->SetValue($item["hash"]);
                $osProveedor->nit->SetValue($item["nit"]);
                $osProveedor->razon_social->SetValue($item["razon_social"]);
                $osProveedor->contacto->SetValue($item["contacto"]);
                $osProveedor->cargo_contacto->SetValue($item["cargo_contacto"]);
                $osProveedor->direccion->SetValue($item["direccion"]);
                $osProveedor->tel_fijo->SetValue($item["tel_fijo"]);
                $osProveedor->tel_celular->SetValue($item["tel_celular"]);
                $osProveedor->correo->SetValue($item["correo"]);
                $osProveedor->web->SetValue($item["web"]);
                $osProveedor->estado->SetValue($item["estado"]);

                $listaProveedor[] = $osProveedor;                
            }            
        }
        
        return $listaProveedor;//devolver una lista[]
    }

    function GetDataProveedor($_hash)
    {
        $sql = "SELECT * FROM `proveedor` WHERE hash='$_hash'";

        $res = $this->Execute($sql);

        $listaProveedor = array();

        if ($this->ContainsData($res))
        {
            $data = $this->DataListStructure($res);
            
            foreach($data as $item)
            {
                $osProveedor = new Structure_Proveedor;

                $osProveedor->idProveedor->SetValue($item["idProveedor"]);
                $osProveedor->hash->SetValue($item["hash"]);
                $osProveedor->nit->SetValue($item["nit"]);
                $osProveedor->razon_social->SetValue($item["razon_social"]);
                $osProveedor->contacto->SetValue($item["contacto"]);
                $osProveedor->cargo_contacto->SetValue($item["cargo_contacto"]);
                $osProveedor->direccion->SetValue($item["direccion"]);
                $osProveedor->tel_fijo->SetValue($item["tel_fijo"]);
                $osProveedor->tel_celular->SetValue($item["tel_celular"]);
                $osProveedor->correo->SetValue($item["correo"]);
                $osProveedor->web->SetValue($item["web"]);
                $osProveedor->estado->SetValue($item["estado"]);

                $listaProveedor[] = $osProveedor;                
            }            
        }
        
        return $listaProveedor;//devolver una lista[]
        
        

    }

    function VerificarProveedor($_idProveedor, $_razonSocial, $_nit)
    {
        if ($_idProveedor == Null) 
        {
            
            $sql = "SELECT * FROM `proveedor` WHERE razon_social='$_razonSocial' AND nit=$_nit";

            $res = $this->Execute($sql);

            if ($this->ContainsData($res))
            {
                return true;

            }
            else
            {
                return false;
            }

        }
        else
        {
            $sql = "SELECT * FROM `proveedor` WHERE  nit=$_nit AND hash!=$_idProveedor";

            $res = $this->Execute($sql);

            if ($this->ContainsData($res))
            {
                return true;
            }
            else
            {
                return false;
            }

        }
        


        
        
    }

    function SaveProveedor($_osProveedor)
    {
        $sql = "INSERT INTO `proveedor` VALUES (
                ". $_osProveedor->idProveedor->GetValue().",
                '".$_osProveedor->hash->GetValue()."',
                '".$_osProveedor->nit->GetValue()."',
                '".$_osProveedor->razon_social->GetValue()."',
                '".$_osProveedor->contacto->GetValue()."',
                '".$_osProveedor->cargo_contacto->GetValue()."',
                '".$_osProveedor->direccion->GetValue()."',
                '".$_osProveedor->tel_fijo->GetValue()."',
                '".$_osProveedor->tel_celular->GetValue()."',
                '".$_osProveedor->correo->GetValue()."',
                '".$_osProveedor->web->GetValue()."',
                '".$_osProveedor->estado->GetValue()."')";

        $res = $this->Execute($sql);

        $id   = $this->GetLastIdAutoGenerated();
        $hash = sha1($id);
        $sql2 = "UPDATE proveedor SET hash = '".$hash."' WHERE idProveedor = " . $id;
        $res2 = $this->Execute($sql2);
        
        $r = ($res and $res2) ? true : false;
        return $r;
    }

    function UpdateProveedor($_osProveedor)
    {
        $sql = "UPDATE proveedor SET
                    nit='".$_osProveedor->nit->GetValue()."',
                    razon_social='".$_osProveedor->razon_social->GetValue()."',
                    contacto='".$_osProveedor->contacto->GetValue()."',
                    cargo_contacto='".$_osProveedor->cargo_contacto->GetValue()."',
                    direccion='".$_osProveedor->direccion->GetValue()."',
                    tel_fijo='".$_osProveedor->tel_fijo->GetValue()."',
                    tel_celular='".$_osProveedor->tel_celular->GetValue()."',
                    correo='".$_osProveedor->correo->GetValue()."',
                    web='".$_osProveedor->web->GetValue()."',
                    estado='".$_osProveedor->estado->GetValue()."'
                WHERE hash='".$_osProveedor->hash->GetValue()."'";
        $res = $this->Execute($sql);

        return $res;
    }

    function DeleteProveedor($_hash)
    {
        $sql = "Update proveedor set estado = 'Inactivo' where hash = '" . $_hash . "'";
        $res = $this->Execute($sql);
        
        return $res;
    }

    function ActiveProveedor($_hash)
    {
        $sql = "Update proveedor set estado = 'Activo' where hash = '" . $_hash . "'";
        $res = $this->Execute($sql);
        
        return $res;
    }

}